##springdoc.api-docs.enabled=false
##springdoc.swagger-ui.enabled=false
##springdoc.packages-to-scan=com.jasmitaprocoder.spring.swagger.controller
#springdoc.swagger-ui.path=/jasmitaprocoder-documentation
#springdoc.api-docs.path=/jasmitaprocoder-api-docs
##springdoc.swagger-ui.operationsSorter=method
##springdoc.swagger-ui.tagsSorter=alpha
#springdoc.swagger-ui.tryItOutEnabled=true
#springdoc.swagger-ui.filter=true
#
#jasmitaprocoder.openapi.dev-url=http://localhost:8080
#jasmitaprocoder.openapi.prod-url=https://jasmitaprocoder-api.com
#jasmitaprocoder.openapi.staging-url=https://staging.jasmitaprocoder-api.com

server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
